//File
export const GET_FILES = 'GET_FILES'
export const SELECT_FILE = 'SELECT_FILE'
export const SELECT_ALL_FILES = 'SELECT_ALL_FILES'
export const DESELECT_FILE = 'DESELECT_FILE'
export const DESELECT_ALL_FILES = 'DESELECT_ALL_FILES'
